name: System-Health-Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-everything:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t health-app .

      - name: Run Application
        run: docker compose up -d

      - name: Test Output
        run: |
          docker ps
          docker logs $(docker ps -q)
